"""
FHE Pipeline Validation Runner

Runs the fhe_pipeline.DataMinimizationPipeline against a batch of synthetic
medical signals and reports:

  - Round-trip reconstruction error  (|decrypt(encrypt(features)) - features|)
  - Throughput (records/second)
  - Data minimization ratio  (feature_dim / raw_dim)
  - Audit log integrity check

No real patient data is used.  The synthetic signals are generated by
synthetic_medical_signal.py.

Usage
-----
    # Quick validation (50 records, dim 128, features 32):
    python validation/run_fhe_validation.py

    # Larger run, save JSON report:
    python validation/run_fhe_validation.py \\
        --n-samples 200 --signal-dim 512 --feature-dim 64 \\
        --output validation/fhe_validation_report.json

Output columns
--------------
  vector_size    : raw signal dimensionality
  feature_dim    : extracted feature dimensionality
  n_samples      : number of records processed
  mean_error     : mean absolute reconstruction error of feature vectors
  max_error      : worst-case reconstruction error
  throughput_rps : records processed per second (encrypt + extract + decrypt)
  minimization   : feature_dim / vector_size (lower = more data minimization)
  audit_ok       : True when audit log has one entry per processed record
  mode           : "tenseal" or "mock"
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np

# ---------------------------------------------------------------------------
# Path setup — allow running from repo root or from validation/
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
_FHE_DIR = _REPO_ROOT / "fhe-feature-extraction"
_VAL_DIR = _REPO_ROOT / "validation"
for _p in (_FHE_DIR, _VAL_DIR):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from fhe_pipeline import TENSEAL_AVAILABLE, DataMinimizationPipeline, FHEContext, FHEFeatureExtractor  # noqa: E402
from synthetic_medical_signal import generate_dataset  # noqa: E402


# ---------------------------------------------------------------------------
# Validation core
# ---------------------------------------------------------------------------


def validate_pipeline(
    n_samples: int = 50,
    signal_dim: int = 128,
    feature_dim: int = 32,
    seed: int = 0,
) -> dict[str, Any]:
    """
    Run the FHE pipeline against synthetic signals and return a result dict.

    Parameters
    ----------
    n_samples:   Number of synthetic records to process.
    signal_dim:  Dimensionality of each input signal (raw data).
    feature_dim: Number of features extracted per record.
    seed:        Random seed for reproducible synthetic data.

    Returns
    -------
    Dictionary with validation metrics (see module docstring for column list).
    """
    X, _, _ = generate_dataset(n_samples=n_samples, signal_dim=signal_dim, seed=seed)

    ctx = FHEContext()

    # Use a fixed random projection for reproducibility
    rng = np.random.default_rng(seed)
    W_raw = rng.standard_normal((feature_dim, signal_dim))
    # Orthonormalise: for feature_dim < signal_dim, svd(..., full_matrices=False)
    # returns Vt with shape (feature_dim, signal_dim) — those are orthonormal rows.
    _, _, Vt = np.linalg.svd(W_raw, full_matrices=False)
    W = Vt  # shape (feature_dim, signal_dim)

    extractor = FHEFeatureExtractor(
        input_dim=signal_dim,
        feature_dim=feature_dim,
        fhe_context=ctx,
        projection_matrix=W,
    )
    pipeline = DataMinimizationPipeline(extractor)

    # Compute reference features in plaintext to measure reconstruction error
    reference_features = (W @ X.T).T  # shape (n_samples, feature_dim)

    errors: list[float] = []
    t_start = time.perf_counter()

    for i, (record, ref_feat) in enumerate(zip(X, reference_features)):
        extracted = pipeline.process(
            data_id=f"val-{i:05d}",
            plaintext_input=record,
            requester="validation_runner",
            purpose="fhe_round_trip_check",
        )
        err = float(np.abs(extracted - ref_feat).mean())
        errors.append(err)

    elapsed = time.perf_counter() - t_start

    audit_log = pipeline.get_audit_log()
    audit_ok = (
        len(audit_log) == n_samples
        and all(not entry["raw_data_returned"] for entry in audit_log)
    )

    return {
        "vector_size": signal_dim,
        "feature_dim": feature_dim,
        "n_samples": n_samples,
        "mean_error": round(float(np.mean(errors)), 8),
        "max_error": round(float(np.max(errors)), 8),
        "throughput_rps": round(n_samples / elapsed, 2),
        "minimization_ratio": round(feature_dim / signal_dim, 4),
        "audit_ok": audit_ok,
        "mode": "tenseal" if TENSEAL_AVAILABLE else "mock",
    }


# ---------------------------------------------------------------------------
# Multi-configuration sweep
# ---------------------------------------------------------------------------


def run_sweep(
    configs: list[dict[str, int]] | None = None,
) -> list[dict[str, Any]]:
    """
    Validate across multiple (signal_dim, feature_dim) configurations.

    Default configurations mirror the benchmark runner sizes.
    """
    if configs is None:
        configs = [
            {"signal_dim": 128,  "feature_dim": 16,  "n_samples": 50},
            {"signal_dim": 512,  "feature_dim": 32,  "n_samples": 30},
            {"signal_dim": 2048, "feature_dim": 64,  "n_samples": 10},
        ]
    return [validate_pipeline(**cfg) for cfg in configs]


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def _print_table(results: list[dict[str, Any]]) -> None:
    header = (
        f"  {'dim':>6}  {'feat':>5}  {'n':>4}  "
        f"{'mean_err':>10}  {'max_err':>10}  "
        f"{'rps':>8}  {'minim':>6}  {'audit':>6}  {'mode':>8}"
    )
    sep = "  " + "─" * (len(header) - 2)
    print("\n  FHE Pipeline Validation Results")
    print(sep)
    print(header)
    print(sep)
    for r in results:
        print(
            f"  {r['vector_size']:>6}  {r['feature_dim']:>5}  {r['n_samples']:>4}  "
            f"{r['mean_error']:>10.2e}  {r['max_error']:>10.2e}  "
            f"{r['throughput_rps']:>8.1f}  {r['minimization_ratio']:>6.3f}  "
            f"{'ok' if r['audit_ok'] else 'FAIL':>6}  {r['mode']:>8}"
        )
    print(sep)
    print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="run_fhe_validation",
        description="Validate FHE round-trip error and throughput on synthetic signals.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--n-samples",   type=int, default=50)
    p.add_argument("--signal-dim",  type=int, default=128)
    p.add_argument("--feature-dim", type=int, default=32)
    p.add_argument("--seed",        type=int, default=0)
    p.add_argument("--sweep",       action="store_true",
                   help="Run the default multi-config sweep instead of a single config.")
    p.add_argument("--output",      type=str, default=None,
                   help="Write JSON report to FILE.")
    return p


def main(argv: list[str] | None = None) -> None:
    args = _build_parser().parse_args(argv)

    if args.sweep:
        results = run_sweep()
    else:
        results = [validate_pipeline(
            n_samples=args.n_samples,
            signal_dim=args.signal_dim,
            feature_dim=args.feature_dim,
            seed=args.seed,
        )]

    _print_table(results)

    # Validation gate: fail if any audit failed or mean_error > 1e-4
    failed = [r for r in results if not r["audit_ok"] or r["mean_error"] > 1e-4]
    if failed:
        print(f"  [FAIL] {len(failed)} configuration(s) failed validation.", file=sys.stderr)
        sys.exit(1)
    else:
        print("  [✓] All configurations passed.")

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            json.dump({"schema_version": "1.0", "results": results}, fh, indent=2)
        print(f"  [✓] Report written to {args.output}")


if __name__ == "__main__":
    main()
